services:
  signaling:
    build:
      context: .
      dockerfile: docker/Dockerfile.signaling
    ports:
      - "3000:3000"
      - "3443:3443" # optional HTTPS
    environment:
      - NODE_ENV=production
      - ENABLE_HTTPS=${ENABLE_HTTPS:-0}
      - HTTPS_PORT=3443
      - MODE=${MODE:-wasm}
    volumes:
      - ./certs:/app/certs:ro
      - ./models:/app/models:ro
    networks:
      - webrtc-network
    profiles:
      - wasm
      - server

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - MODE=${MODE:-server}
      - GPU_ENABLED=${GPU_ENABLED:-false}
    volumes:
      - ./models:/app/models
    networks:
      - webrtc-network
    profiles:
      - server

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8002:8002"
    environment:
      - MODE=${MODE:-wasm}
    volumes:
      - ./models:/app/models
    networks:
      - webrtc-network
    profiles:
      - legacy

networks:
  webrtc-network:
    driver: bridge
